### PR TITLE
add linter attribute to ignore response codes

### PR DESCRIPTION
**Pull request by mikeclimbrock**

### CODE REVIEW

**Comment by mbryzek** [comment]
lgtm - assuming this is for the shopify apis?

**Comment by mikeclimbrock** [comment]
it is for 5 of our internal APIs - 
billing-internal

Resource payments POST /internal/:organization/payments/:reference/close: Missing response codes: 422
payment-internal

Resource keys POST /:organization/keys: Missing response codes: 422
Resource passphrases POST /:organization/passphrases/:id/authentications: Missing response codes: 401
Resource passphrases POST /:organization/passphrases: Missing response codes: 401
session-internal

Resource sessions GET /sessions/:session: Missing response codes: 401
Resource sessions POST /sessions: Missing response codes: 401
Resource sessions PUT /sessions/:session/reset: Missing response codes: 401
Resource sessions PUT /sessions/:session: Missing response codes: 401
shopify-internal

Resource carts GET /carts/:id.html: Missing response codes: 401
Resource carts GET /carts/🆔 Missing response codes: 401
Resource carts POST /carts/:id/add: Missing response codes: 401
Resource carts POST /carts/:id/change: Missing response codes: 401
Resource carts POST /carts/:id/clear: Missing response codes: 401
Resource carts POST /carts/:id/orders: Missing response codes: 401
Resource consume POST /:organization/consume/:myshopify_domain/product/deleted: Missing response codes: 401
Resource consume POST /:organization/consume/:myshopify_domain/product/upserted: Missing response codes: 401
Resource experience_countries GET /experience-countries/:myshopify_domain: Missing response codes: 401
Resource variant_prices GET /variants/:myshopify_domain/prices/:id/experience/🔑 Missing response codes: 401
Resource variant_prices GET /variants/:myshopify_domain/prices/:variant_id: Missing response codes: 401
Resource variant_prices GET /variants/:myshopify_domain/prices: Missing response codes: 401
user-internal

Resource user_one_time_tokens POST /users/tokens/redeem: Missing response codes: 401, 422
Resource user_one_time_tokens POST /users/tokens: Missing response codes: 422

**Comment by mikeclimbrock** [comment]
I'll gonthrough and use this where appropriate and implement response codes if necessary in others

**Comment by mbryzek** [comment]
cool - it feels like for our own APIs, we should be able to document... and we should because eventually these will likely be public.

**Pull request merged**
