### PR TITLE
Exclude organization from GET resource linting

### PR DESCRIPTION
**Pull request by ericluria**

### CODE REVIEW

**Comment by ericluria** [comment]
The reason for this PR is because of linting that prevents building the API with [this organization resource](https://github.com/flowcommerce/api/blob/master/spec/organization.json#L193-L208) that returns all currencies for an organization.

This PR still needs work since (I think) it's going to fail validation [here](https://github.com/flowcommerce/api-build/blob/master/src/main/scala/io/flow/lint/linters/CommonParameterTypes.scala#L34-L43) since the aforementioned endpoint returns an array.

**Comment by ericluria** [comment]
Alright, tested it out locally and I'm still getting two more errors -
```
SUMMARY: 1 ERROR
organization
  - Resource organizations GET /organizations/:id/settings/currencies Parameter id: Maximum was not specified - should be 100
  - Resource organizations GET /organizations/:id/settings/currencies Parameter id: Type expected[[string]] but found[string]
```

More work to do..

**Comment by ericluria** [comment]
The error in my last comment has been temporarily fixed by renaming `:id` to `:organization_id`, but the API build won't pass until this PR is merged and released.

**Comment by mikeclimbrock** [comment]
lgtm

**Pull request merged**
